[package]
name = "dartfrog_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
anyhow = "1.0"
kinode_process_lib = { git = "https://github.com/kinode-dao/process_lib", tag = "v0.8.0" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
